name: Build ICS
on:
  schedule:
    - cron: "*/1 * * * *"    # her 1 dakikada bir
  workflow_dispatch:

permissions:
  contents: write            # <-- push izni

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install notion-client

      - name: Ensure docs/ exists and disable Jekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Generate ICS
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FEED_NAME: "Flashcards"
          FEED_TZ: "Europe/Istanbul"
        run: |
          python generate_ics.py
          test -f docs/calendar.ics

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/calendar.ics
          # değişiklik yoksa çık
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "Update ICS"
          # olası non-fast-forward için rebase çek
          git pull --rebase origin ${{ github.ref_name }} || true
          git push
