name: Build ICS
on:
  schedule:
    - cron: "*/6 * * * *"   # ~6 dakikada bir (GitHub en erken ~5 dk tetikler)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ics-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euxo pipefail
          python -V
          pip install --upgrade pip
          pip install notion-client

      - name: Ensure docs/ and disable Jekyll
        run: |
          set -euxo pipefail
          mkdir -p docs
          touch docs/.nojekyll

      - name: Generate ICS (verbose)
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FEED_NAME: "Flashcards"
          FEED_TZ: "Europe/Istanbul"
        run: |
          set -euxo pipefail
          python - <<'PY'
          import os, sys, traceback
          import generate_ics as gen
          try:
              ics = gen.generate_ics()
              os.makedirs("docs", exist_ok=True)
              with open("docs/calendar.ics", "w", encoding="utf-8", newline="\r\n") as f:
                  f.write(ics)
              print("WROTE docs/calendar.ics, bytes:", len(ics))
          except Exception:
              traceback.print_exc()
              sys.exit(1)
          PY
          test -f docs/calendar.ics
          wc -c docs/calendar.ics || true

      - name: Commit & push (conflict-free)
        env:
          BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Çalışma ağacını her run'da remote'ın son haline sabitle
          git fetch origin "$BRANCH"
          git checkout -B "$BRANCH" "origin/$BRANCH"

          # Sadece değişiklik varsa commit et
          git add docs/calendar.ics docs/.nojekyll || true
          if git diff --cached --quiet; then
            echo "No changes"; exit 0
          fi
          git commit -m "Update ICS"
          git push origin "$BRANCH"
