name: Build ICS
on:
  schedule:
    - cron: "*/1 * * * *"     # her 1 dakikada bir
  workflow_dispatch:

permissions:
  contents: write

# Aynı anda iki run çakışmasın
concurrency:
  group: ics-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install notion-client

      - name: Ensure docs/ exists and disable Jekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Generate ICS
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FEED_NAME: "Flashcards"
          FEED_TZ: "Europe/Istanbul"
        run: |
          python generate_ics.py
          test -f docs/calendar.ics

      - name: Commit & push (with rebase + retry)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Sadece değişiklik varsa commit
          git add docs/calendar.ics
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Update ICS"

          # Uzak değişmişse rebase'le ve tekrar dene
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || true

          if git push; then
            echo "Pushed OK"
          else
            echo "Push failed once, retrying after rebase…"
            git fetch
